
name: Build external repo wheel (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Build wheel
        run: |
          git clone --depth 1 --branch main https://github.com/w9PcJLyb/w9-pathfinding.git
          cd w9-pathfinding
          python -m pip install -U pip
          python -m pip install -U build setuptools wheel cython
          python -m build --wheel

      - name: 上传Whl文件
        uses: actions/upload-artifact@v4
        with:
           name: wheels-py${{ matrix.python-version }}
           path: dist/*.whl
